# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
