# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactapp', '0002_contact_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='completed',
        ),
    ]
